## INTRODUCTION TO NUMPY
Data science have became very popular in the last years. It is a very broad field and it is not easy to define it. In general, it is the process of extracting knowledge from data. It is a multidisciplinary field that combines statistics, mathematics, computer science and domain knowledge. It is used in many fields such as finance, marketing, biology, physics, etc. In this notebook, we will focus on the basics of data science and we will use the Python programming language.

**WHAT IS NUMPY?**

> **Numpy** is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. It is the fundamental package for scientific computing with Python.

It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Let's get started!

**Installing Numpy**

In [1]:
# pip command for installing numpy: pip install numpy

%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


**Importing Numpy**


In [2]:
# Importing numpy
import numpy # 1st way

In [3]:
import numpy as np # 2nd way (recommended)

## Arrays - Part 1
### What is an array?

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

### Why use arrays?
We use arrays to store multiple values of same kind in one single variable instead of creating separate variables for each value.

## Numpy Arrays
In Python we have lists that serve the purpose of arrays, but they are slow to process. And the main reason behind this is that lists in Python are very general. They can contain heterogeneous values. So Python has a library called **Numpy** that handles matrices very efficiently and has a large number of optimized built-in mathematical functions.


**What is N-Dimensional array?**

> N-Dimensional array is a multidimensional array of items of same type (can contain multiple data types) which can be indexed by a tuple of positive integers.

We can say that a numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

like 1-d array is called as vector, 2-d array is called as matrix, 3-d array is called as tensor and so on...

### **Creating a Numpy Array**


In [6]:
import numpy as np

example_list = [1,2,3,4,5]

example_numpy_array = np.array(example_list)

print('example_numpy_array: ', example_numpy_array)
print('type of example_numpy_array: ', type(example_numpy_array))

example_numpy_array:  [1 2 3 4 5]
type of example_numpy_array:  <class 'numpy.ndarray'>


> **Arrays are homogeneous data structures (i.e., they contain elements of the same type).**

In [9]:
import numpy as np

example_list = [1,2,3,4,5.0002]

example_numpy_array = np.array(example_list)

print('example_numpy_array: ', example_numpy_array)
print('type of example_numpy_array: ', type(example_numpy_array))

example_numpy_array:  [1.     2.     3.     4.     5.0002]
type of example_numpy_array:  <class 'numpy.ndarray'>


**2-Dimensional Arrays**
2-Dimensional Arrays are the most commonly used array. In 2D arrays, the data is stored in row and columns. We can create a 2D array using the array() method.

like this : 
| 1 | 2 | 3 |
|---|---|---|
| 4 | 5 | 6 |
| 7 | 8 | 9 |

Array with 3 rows and 3 columns ( 2-D array )

- **Creating a 2-D array**


In [12]:
import numpy as np

list_1 = [[1,2,3],[4,5,6],[7,8,9]]

array2 = np.array(list_1)
print('array2: \n', array2)


array2: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


**Creating Numpy Arrays with arange()**

In [13]:
import numpy as np
array3 = np.arange(0,9)
print('array3: ', array3)

array3:  [0 1 2 3 4 5 6 7 8]


In [19]:
import numpy as np
array4 = np.arange(0,6).reshape(2,3)
print('array4: \n', array4)

array4: 
 [[0 1 2]
 [3 4 5]]


In [20]:
import numpy as np

array1 = np.zeros(5)
print('array1: ', array1)

array1:  [0. 0. 0. 0. 0.]


In [21]:
# 2D array of zeros
array2 = np.zeros((3,4))
print('array2: \n', array2)

array2: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
# array of ones
array3 = np.ones(5)
print('array3: ', array3)

array3:  [1. 1. 1. 1. 1.]


In [1]:
import numpy as np

list5 = ['lawda','lassun']

# array of strings
array5 = np.array(list5)
print('array5: ', array5)
print('type of array5: ', type(array5))

array5:  ['lawda' 'lassun']
type of array5:  <class 'numpy.ndarray'>


> #### **Done for today! Now I am going to sleep :D**