## **Operation On Numpy Array**

### **1. Indexing the NumPy Array**

As array elements got contigous memory allocation and their index value starts from zero. So we can simply access their index value. In 2D or Multi-dimentional array the indexing works same but we need to use index value of all present dimention.We will learn later on about this.


Let's start with simple **Indexing od 1-D Array!**

**1. Indexing of 1-D Array**

To access an element fron 1-D Array we can simply use its index value.As Index starts from `0` which means that if array has 5 elements then it has a total index of `4` as indexing counts from `0`.

*Total Index of 1-D array =* `N(num of total element present in array)-1`

*Index of an element =* `n(postion of element)-1`

In [1]:
import numpy as np

array_1 = np.array([10,20,30,40])
print(array_1[0])

10


In [3]:
print(array_1[2]) # index 2 = 2 + 1 means element at third position

30


In [4]:
print(array_1[7])

IndexError: index 7 is out of bounds for axis 0 with size 4

> IndexError

This happens when we try to access element which is out of the index like here we have [10,20,30,40] say (1,2,3,4) or 4 elements which means if we count from `0` then what we got that we only have size of 3 and we are trying to access an element on index 7 which means their must be atleast 8 element should be present in array. 

**2. Indexing of 2-D Array**

To index an element of a 2-D Array we use its index value at Row and its index value at column.

In [5]:
import numpy as np

array_2 = np.array([
    # 0,1,2
    [1,2,3],# 0
    [4,5,6],# 1
    [7,8,9] # 2
])

In [6]:
# let access element 1 or 1-1 = 0 element at 0 index
print(array_2[0][0])

1


In [7]:
print(array_2[0][1])

2


In [8]:
print(array_2[0][2])

3


In [9]:
print(array_2[1][0])

4


### **Sorting NumPy Array**

**1. Sorting 1-D Array**
`Numpy` has built in function to sort arrays. These are the following built in function to sort an array :

- `np.sort()`- It will return a **sorted copy** of an array.
- `np.argsort()` - Will return the indices that would sort an array
- `ndarray.sort()` - use array name and sort it in-place

In [1]:
# using np.sort
import numpy as np
x = np.array([7,3,1,4,5,6])
y = np.sort(x)
y

array([1, 3, 4, 5, 6, 7])

In [3]:
y = np.sort(x)[::-1]
y

array([7, 6, 5, 4, 3, 1])

In [6]:
y = np.argsort(x)
y

array([2, 1, 3, 4, 5, 0], dtype=int64)

**2. Sorting of 2-D array**

In [6]:
import numpy as np

x = np.array([
    [12,13,11],
    [16,15,14],
    [19,18,17]
])

x

array([[12, 13, 11],
       [16, 15, 14],
       [19, 18, 17]])

In [8]:
x_sorted = np.sort(x)
x_sorted

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [10]:
x_sorted_2 = np.argsort(x,axis=0)
x_sorted_2

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [11]:
x_sorted_2 = np.argsort(x,axis=1)
x_sorted_2

array([[2, 0, 1],
       [2, 1, 0],
       [2, 1, 0]], dtype=int64)

In [12]:
x.sort()
x

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### **Slicing in NumPy Arrays**
> Slicing is a way to extract a subset of data from a numpy array.

**1. Slicing in 1-D Numpy array**

In [1]:
import numpy as np

array1 = np.array([10,20,30,40,50,60,70])

In [3]:
print(array1[0:3])

[10 20 30]


In [4]:
print(array1[1:3])

[20 30]


In [5]:
print(array1[1:6:2])

[20 40 60]


In [6]:
print(array1[-1:-3:-1])

[70 60]


In [7]:
print(array1[::2])

[10 30 50 70]


In [8]:
print(array1[::-1])

[70 60 50 40 30 20 10]


**2. Slicing in 2-D Array**

In [9]:
import numpy as np

array2 = np.array([
    #0,1,2,3
    [15,16,17], # 0
    [18,19,20], # 1
    [21,22,23], # 2
    [24,25,26] # 3
])

In [10]:
print(array2[1,])

[18 19 20]


In [12]:
print(array2[:,1])

[16 19 22 25]


In [13]:
print(array2[1:3,1:3])

[[19 20]
 [22 23]]


In [14]:
print(array2[1:3,])

[[18 19 20]
 [21 22 23]]


In [16]:
print(array2[:,1:3])

[[16 17]
 [19 20]
 [22 23]
 [25 26]]


In [17]:
print(array2[1:3,1])

[19 22]


In [18]:
print(array2[1:3,:1])

[[18]
 [21]]


> **Okay done for this topic :D**