## **NumPY Attributes**
> **NumPy** is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

### **NumPy Array Attributes List**

| Attribute | Description |
| --- | --- |
| **ndim** | This array attribute returns the number of array dimensions. |
| **shape** | This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array. |
| **size** | This array attribute returns the number of elements in the array. |
| **dtype** | This array attribute returns an object describing the type of the elements in the array. |
| **itemsize** | This array attribute returns the size in bytes of each element of the array. |

Let's start studying these attributes one by one.

In [1]:
import numpy as np
list1 = [[1,2,3],[4,5,6],[7,8,9]]
array1 = np.array(list1)

1. `ndim` - NumPy Array Dimensions

In [2]:
print('Array 1:\n', array1)
print('Dimension of array1: ', array1.ndim)

Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of array1:  2


In [3]:
import numpy as np

array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print('Array 3:\n', array3)
print('Dimension of array3: ', array3.ndim)

Array 3:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension of array3:  3


2. `shape` - NumPy Array Shape

In [4]:
## Shape of an array
import numpy as np
list1 = [[1,2,3],[4,5,6],[7,8,9]]
array1 = np.array(list1)
print('Shape of array1: ', array1.shape)

Shape of array1:  (3, 3)


In [5]:
print('Shape of array3: ', array3.shape)

Shape of array3:  (2, 3, 3)


3. `size` - NumPy Array Size


In [6]:
print('Size of array1: ', array1.size)

Size of array1:  9


In [7]:
print('Size of array3 : ', array3.size)

Size of array3 :  18


4. `dtype` - NumPy Array Data Type

In [8]:
print('Data type of array1: ', array1.dtype)
print('Data type of array3: ', array3.dtype)

Data type of array1:  int32
Data type of array3:  int32


> The `dtype` attribute of NumPy arrays returns the data type of the elements in the array. And the `itemsize` attribute returns the size of each element in bytes.

In [9]:
# itemsize
print('Item size of array1: ', array1.itemsize)
print('Item size of array3: ', array3.itemsize)

Item size of array1:  4
Item size of array3:  4


### *Done for now! Good night!*